#!/usr/bin/env bash

random_wallpaper() {

	# A full path into wallpaper directory
	WALLPATH="$HOME/Pictures/Wallpaper"

	# Get a one random wallpaper
	random_wallpaper=$(ls $WALLPATH | sort -R | tail -n1)

	# Set a random wallpaper
	feh --bg-scale $WALLPATH/$random_wallpaper &
}

random_wallpaper

# Set Xresources
[[ -f ~/.Xresources ]] && xrdb -merge ~/.Xresources

# Keyboard extras
# Change language and swap escape with caps lock
setxkbmap -model pc105 -layout us,ru -option caps:swapescape,grp:win_space_toggle

# Startup Polybar
polybar &
